# theme: jekyll-theme-minimal
# title: Rishit's homepage
# description: Bookmark this to keep an eye on my project updates!

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Rishit's Portfolio"

# A description of your site for meta tag, search engine results.
description: "Bookmark this tab to keep an eye on Rishit's project updates"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

### Markdown
I am an Undergrad Specialising in Artificial intelligence, Machine Learning & Deep Learning. I am open to Collaborate, Contribute and Connect with Developers, Researchers, Content Creators, Inventors, CEO’S, Tech Enthusiasts, Authors, Influencers and many more Diverse Communities.

My Aim is to Build A Company and a Community that bridges the gap between Society and Technology that could contribute to the Sustainability and the Neocortical Capacity of the human kind as we advance into the future.

I think Simplicity and Creative Imagination is the best Evolution.

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://scriptor-jekyll.netlify.com"

# # Favicon
# favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: Portfolio
    url: /portfolio/
  - text: Projects & Publications
    url: /projects/
  - text: Accolades
    url: /accolades/
  - text: CV
    url: /cv/

# The shortname for your Disqus site to enable comments.
disqus: justgoodthemes

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "&copy; Rishit Kapoor all rights reserved."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

